[project]
name = "a3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "mysql-connector-python>=9.5.0",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
]

